### ISSUE TITLE
Inconsistent number of files in AudioCaps dataset

### ISSUE THREAD

**Issue by MorenoLaQuatra** [cdjkim/audiocaps#17]
Hi all,

Thank you for creating and sharing the AudioCaps dataset. I found it to be very useful.

However, I noticed that the number of files in each set (training, validation, and test) is very different from the numbers presented in the official repository. Here are the number of files I obtained:

| Set        | Number of files |
|------------|----------------|
| Training   | 45458          |
| Validation | 2245           |
| Test       | 4440           |

However, the original values in the repository are:

| Set        | Number of files |
|------------|----------------|
| Training   | 49,838         |
| Validation | 495            |
| Test       | 975            |
| Total      | 51,308         |

I also noticed that the csv files contain more rows than what is proposed as the validation and test set, and are more similar to the number of files I obtained.

I am wondering if there is something I am missing or if there is an issue with the original values provided in the repository. Please let me know if there is any clarification needed or if there are any updates to the dataset.

I also created a python package to download the dataset very easily: https://github.com/MorenoLaQuatra/audiocaps-download

Thank you for your time and for providing this valuable resource.

Best regards,

Moreno La Quatra

**Comment by duduOliver** [comment]
Hello,
I have no hints for your issue, but I just found an AudioCaps dataset that is easy to download and prepare from this project: [https://github.com/XinhaoMei/ACT](https://github.com/XinhaoMei/ACT) 
Hope it helps!

**Comment by MorenoLaQuatra** [comment]
Yes, it helps a lot! Thank you!

**Comment by piyushsinghpasi** [comment]
Hii MorenoLaQuatra (not tagging you, since the issue is slightly old), even I am facing similar issue, I think its the unique number of files in the split and NOT the number of instances in the split.

Other than that I don't see any reason of discrepancy. I hope people report number on all instances (some videos are now unavailable/private).

The drive link contains only 10 sec audios (and count doesn't match the csvs here on git)

I think csv on this git repo are correct, as shown in the audiocaps paper:
![image](https://github.com/user-attachments/assets/b300ad4e-1f10-4172-afcd-229adaedd4e1)

Leaving this comment in case someone also gets the same issue.
I appreciate corrections, feel free for it :)

**Comment by MorenoLaQuatra** [comment]
Thank you for additional context!
